version: "3.8"
# un nouveau commentaire
volumes:
  mariaviget: #déclaration du volume pour la base

services:

  # container de bdd
  vigetbase: #nom de service
    container_name: baseviget
    image: mariadb:latest
    ports:
      - '3306:3306'
    volumes:
      - mariaviget:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: vigetadmin
      MYSQL_DATABASE: viget
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  # container php
  vigetphp:
    container_name: phpviget
    build:
      context: ./php
    #    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '9000:9000'
    environment:
      DEBUG: '1'
      PHP_DISPLAY_ERRORS: '1'
      PHP_POST_MAX_SIZE: "100M"
      PHP_UPLOAD_MAX_FILESIZE: "100M"
      TZ: UTC
    volumes:
      - ./app:/var/www/html
    depends_on:
      - vigetbase

  # service node
  vigetnode:
    tty: true
    container_name: nodeviget
    build:
      context: ./node
    volumes:
      - ./app:/var/www/html
    restart: always
    environment:
      TZ: UTC
    depends_on:
      - vigetphp

  # server web
  vigetnginx:
    container_name: nginxviget
    image: nginx:stable-alpine
    #    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      TZ: UTC
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx/
    depends_on:
      - vigetphp
      - vigetbase
      - vigetnode